// <auto-generated />
namespace PVenta.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.3.0")]
    public sealed partial class JEv038 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(JEv038));
        
        string IMigrationMetadata.Id
        {
            get { return "201912070411494_JEv038"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
