// <auto-generated />
namespace PVenta.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.3.0")]
    public sealed partial class JEv003 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(JEv003));
        
        string IMigrationMetadata.Id
        {
            get { return "201910301714506_JEv003"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
