// <auto-generated />
namespace PVenta.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.3.0")]
    public sealed partial class JEv00 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(JEv00));
        
        string IMigrationMetadata.Id
        {
            get { return "201910291924040_JEv00"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
